
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LoginLink} from "@kinde-oss/kinde-auth-nextjs/components";
import {LogoutLink} from "@kinde-oss/kinde-auth-nextjs/components";
import {getKindeServerSession} from "@kinde-oss/kinde-auth-nextjs/server";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const {isAuthenticated} = getKindeServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <nav className="px-10 mt-4 bg-red-100 py-3 ">
          <ul className="flex justify-center gap-5 ">

            <li className="border-white border-2 px-2 py-1 text-green-800"><Link href={'/'}>Home</Link></li>
            <li className="border-white border-2 px-2 py-1 text-green-800"><Link href={'/profile'}>profile</Link></li>
            {
              isAuthenticated ? 
              <li className="border-white border-2 px-2 py-1 text-green-800"><LogoutLink>Log out</LogoutLink></li>
              :
            <li className="border-white border-2 px-2 py-1 text-green-800"><LoginLink>Sign in</LoginLink></li>
            }
         
           
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
